export const CharacterTableData = {
  tableLabel: [{ label: '字符', props: 'value' }],
  tableArr: [
    { value: 'a' },
    { value: 'b' },
    { value: 'c' },
    { value: 'd' },
    { value: 'e' },
    { value: 'f' },
    { value: 'g' },
    { value: 'h' },
    { value: 'i' },
    { value: 'j' },
    { value: 'k' },
    { value: 'l' },
    { value: 'm' },
    { value: 'n' },
    { value: 'o' },
    { value: 'p' },
    { value: 'q' },
    { value: 'r' },
    { value: 's' },
    { value: 't' },
    { value: 'u' },
    { value: 'v' },
    { value: 'w' },
    { value: 'x' },
    { value: 'y' },
    { value: 'z' }
  ],
  showID: true
}
